//SPDX-License-Identifier: MIT
pragma solidity 0.8.24;

//==============================================================================
//IMPORTS
//==============================================================================
import "lib/openzeppelin-contracts/contracts/token/ERC20/ERC20.sol";
import "lib/openzeppelin-contracts/contracts/access/AccessControl.sol";
import "lib/openzeppelin-contracts/contracts/token/ERC20/extensions/ERC20Permit.sol";
import "lib/openzeppelin-contracts/contracts/token/ERC20/extensions/ERC20Burnable.sol";

/**
@title SyntheticToken
@notice This contract is used to create a synthetic token that is used to represent future yield that is generated by the protocol
*/
contract SyntheticToken is ERC20, ERC20Permit, ERC20Burnable, AccessControl {}
